/** Canonical server-owned product codes. Never infer access from a plan name. */
export const PRODUCT_CAPABILITY = {
  ORBIT_INTELLIGENCE: "ORBIT_INTELLIGENCE",
  AI_ASSISTANTS: "AI_ASSISTANTS",
} as const;

export const PRODUCT_FEATURE = {
  ORBIT_INTELLIGENCE: "ORBIT_INTELLIGENCE",
  AI_ASSISTANTS: "AI_ASSISTANTS",
  SCHEDULING_INTELLIGENCE: "SCHEDULING_INTELLIGENCE",
  ASSET_INTELLIGENCE: "ASSET_INTELLIGENCE",
  ARTIFACT_INTELLIGENCE: "ARTIFACT_INTELLIGENCE",
} as const;
